// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nodjxylbgzjkdafnjfat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vZGp4eWxiZ3pqa2RhZm5qZmF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MTgxNjAsImV4cCI6MjA2MzQ5NDE2MH0.QtytL5VCEPVLEaG_wCuiVcs_Gj_157XtuZ_2C5mIc1c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);